"""Initial Migrations

Revision ID: 7c988d9620df
Revises: 
Create Date: 2023-06-07 16:09:16.074954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c988d9620df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('modified_on', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('warehouse',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('modified_on', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('input_benchmark_productivity',
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('productivity_experienced_employee', sa.Float(), nullable=False),
    sa.Column('productivity_new_employee', sa.Float(), nullable=False),
    sa.Column('soft_delete_flag', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('modified_on', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_id', 'category_id')
    )
    op.create_table('input_demand',
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('demand', sa.Integer(), nullable=False),
    sa.Column('soft_delete_flag', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('modified_on', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_id', 'category_id', 'date')
    )
    op.create_table('input_requirements',
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('num_current_employees', sa.Integer(), nullable=False),
    sa.Column('plan_from_date', sa.Date(), nullable=True),
    sa.Column('plan_to_date', sa.Date(), nullable=True),
    sa.Column('percentage_absent_expected', sa.Float(), nullable=False),
    sa.Column('day_working_hours', sa.Integer(), nullable=False),
    sa.Column('cost_per_employee_per_month', sa.Integer(), nullable=False),
    sa.Column('total_hiring_budget', sa.Integer(), nullable=False),
    sa.Column('soft_delete_flag', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('modified_on', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('input_requirements')
    op.drop_table('input_demand')
    op.drop_table('input_benchmark_productivity')
    op.drop_table('warehouse')
    op.drop_table('category')
    # ### end Alembic commands ###
